### ISSUE TITLE
Add support to double-quotes keys

### ISSUE THREAD

**Issue by diegoldev** [NawrasBukhari/laravel-translate-scanner#1]
As enhacement, replacing [this regex](https://github.com/NawrasBukhari/laravel-translate-scanner/blob/18c42804634ba6781600d86aa8534475f452b409/src/Command/TranslationHelperCommand.php#L105) with something like this:
`preg_match_all("#$functionName\(\s*[\'|\"](.*?)[\'|\"]\s*\)#", $content, $matches);`
could add support to double-quotes keys, such as
 `@lang("My text to translate")`

I tried to make a PR but the repository is closed to PR.

**Comment by NawrasBukhari** [comment]
fixed here https://github.com/NawrasBukhari/laravel-translate-scanner/releases/tag/1.0.2
